save_results_path: /users/newc6477/VAE/12_Lead_VECG/results/f
seed: 42
epochs: 150
latent_dimension: 8
learning_rate: 0.002
coefficients:
  alpha: 1.0
  beta: 4.0
  gamma: 1.0
coefficients_raise: 50
early_stopping: 60
reconstruction:
  period_plot: 20
  index_sample: 5
