train_dataset:
  name:
  - physionet
  split: 'train'
  shuffle_size: 1024
  batch_size: 1024
val_dataset:
  name:
  - physionet
  split: 'test'
  shuffle_size: 1024
  batch_size: 1024
save_results_path: C:\Users\Thomas Kaprielian\Documents\Master's Thesis\VECG\results\run_5
seed: 42
epochs: 3
latent_dimension: 8
learning_rate: 0.002
coefficients:
  alpha: 1.0
  beta: 4.0
  gamma: 1.0
coefficients_raise: 20
early_stopping: 50
reconstruction:
  period_plot: 20
  index_sample: 5
